# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: article.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'article.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rarticle.proto\"J\n\x07\x41rticle\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\x12\x13\n\x0b\x63reate_time\x18\x04 \x01(\t\"1\n\x0e\x41rticleRequest\x12\x0c\n\x04page\x18\x01 \x01(\x05\x12\x11\n\tpage_size\x18\x02 \x01(\x05\"1\n\x13\x41rticleListResponse\x12\x1a\n\x08\x61rticles\x18\x01 \x03(\x0b\x32\x08.Article\"\"\n\x14\x41rticleDetailRequest\x12\n\n\x02pk\x18\x01 \x01(\x05\x32j\n\x0e\x41rticleService\x12-\n\x04List\x12\x0f.ArticleRequest\x1a\x14.ArticleListResponse\x12)\n\x06\x44\x65tail\x12\x15.ArticleDetailRequest\x1a\x08.Articleb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'article_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ARTICLE']._serialized_start=17
  _globals['_ARTICLE']._serialized_end=91
  _globals['_ARTICLEREQUEST']._serialized_start=93
  _globals['_ARTICLEREQUEST']._serialized_end=142
  _globals['_ARTICLELISTRESPONSE']._serialized_start=144
  _globals['_ARTICLELISTRESPONSE']._serialized_end=193
  _globals['_ARTICLEDETAILREQUEST']._serialized_start=195
  _globals['_ARTICLEDETAILREQUEST']._serialized_end=229
  _globals['_ARTICLESERVICE']._serialized_start=231
  _globals['_ARTICLESERVICE']._serialized_end=337
# @@protoc_insertion_point(module_scope)
